### ISSUE TITLE
import less

### ISSUE THREAD

**Issue by huang6349** [sorrycc/dva-boilerplate-typescript#1]
我在 components 中定义了一个 index.less 文件
第三方插件的“d.ts”我都引入了
项目中我加载ts,tsx文件都很正常
import React, { PropTypes } from 'react';   ---- ok
import { Router, Route } from 'dva/router';  ---- ok
import Header from './common/Header'; ---- ok
但是引入样式文件就会提示无法找到该模块
import styles from './style/index.less';  ---- error
提示：“[ts] Cannot find module './style/index.less'.”
请教大神我该怎么解决这个问题

这是项目配置地址 https://github.com/huang6349/ts-dva

**Comment by huang6349** [comment]
我已经解决了在 *.ts 或者 *.tsx 中加载less文件不能找到模块的方法了
我在项目中增加了一个ambient.d.ts文件来申明非“ *.js, *.jsx, *.ts, *.tsx”文件加载导出文件类型为any

// ambient.d.ts

/**
- 加载"less"文件
  _/
  declare module '_.less' {
  const content: any;
  export default content;
  }

https://github.com/huang6349/ts-dva/commit/66ca7be46236149f67fd1a7ff54b9ef7dfa864be

感谢dvajs团队以及sorrycc大神的付出和贡献

**Comment by sorrycc** [comment]
dva 和 antd 都不要用 dt 的配置，那个不全的，typings 的依赖参考这个库吧。

**Comment by huang6349** [comment]
好的大神，3Q 😊

**Comment by sorrycc** [comment]
这个库增加了 css-modules 的支持，https://github.com/sorrycc/dva-boilerplate-typescript/commit/0358664ca65e9ed5325308ab0e6d4c2185149786

**Comment by huang6349** [comment]
感谢大神的指导，之前的写法只能兼容到Typescript 2以上，现在在Typescript 1.8版本不会抱错了
