### ISSUE TITLE
请问要集成roadhog，来支持typescript，应该怎么写配置？

### ISSUE THREAD

**Issue by baishiup** [sorrycc/dva-boilerplate-typescript#7]
dva-cli是集成了roadhog,我想在这基础上来添加typescript的支持，在roadhog,dva,dva-cli看到相关的issue都无效？

**Comment by baishiup** [comment]
找到了 直接webpack.config.js

**Comment by dkvirus** [comment]
@baishiup 兄弟，你现在的 dva 已经改写成 typescript 了吗？我参照这个工程运行了一下，一直报错，现在不清楚怎么做迁移，能否提供下思路或 demo。
